namespace CSharpPdf.types.enums
{
    public enum HPDF_TransitionStyle
    {
        HPDF_TS_WIPE_RIGHT  = 0, 
		HPDF_TS_WIPE_UP = 1,
		HPDF_TS_WIPE_LEFT = 2, 
		HPDF_TS_WIPE_DOWN = 3, 
		HPDF_TS_BARN_DOORS_HORIZONTAL_OUT = 4,
		HPDF_TS_BARN_DOORS_HORIZONTAL_IN = 5,
		HPDF_TS_BARN_DOORS_VERTICAL_OUT = 6,
		HPDF_TS_BARN_DOORS_VERTICAL_IN = 7, 
		HPDF_TS_BOX_OUT = 8, 
		HPDF_TS_BOX_IN = 9, 
		HPDF_TS_BLINDS_HORIZONTAL = 10, 
		HPDF_TS_BLINDS_VERTICAL = 11, 
		HPDF_TS_DISSOLVE = 12, 
		HPDF_TS_GLITTER_RIGHT = 13, 
		HPDF_TS_GLITTER_DOWN = 14, 
		HPDF_TS_GLITTER_TOP_LEFT_TO_BOTTOM_RIGHT = 15, 
		HPDF_TS_REPLACE = 16, 
		HPDF_TS_EOF  = 17 
    }
}
